/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class JfrmAddHotel extends javax.swing.JFrame {

    /**
     * Creates new form JfrmAddHotel
     */
    public JfrmAddHotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRbtnGrpCategoria = new javax.swing.ButtonGroup();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jRbtnCat1 = new javax.swing.JRadioButton();
        jRbtnCat2 = new javax.swing.JRadioButton();
        jRbtnCat3 = new javax.swing.JRadioButton();
        jRbtnCat4 = new javax.swing.JRadioButton();
        jRbtnCat5 = new javax.swing.JRadioButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jTxtDireccionHotel = new javax.swing.JTextField();
        jTxtNombreHotel = new javax.swing.JTextField();
        jTxtCorreoHotel = new javax.swing.JTextField();
        jTxtTelefonoHotel = new javax.swing.JTextField();
        jCmbCiudadesHotel = new javax.swing.JComboBox<>();
        jCmbxPaiseHotel = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jCmbxPaiseHotel1 = new javax.swing.JComboBox<>();
        jCmbCiudadesHotel1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Nuevo Hotel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Telefono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Ciudad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("País:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Categoría - Estrellas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 10, 50));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 260, 10));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 10, 50));

        jRbtnGrpCategoria.add(jRbtnCat1);
        jRbtnCat1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRbtnCat1.setText("1");
        getContentPane().add(jRbtnCat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jRbtnGrpCategoria.add(jRbtnCat2);
        jRbtnCat2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRbtnCat2.setText("2");
        getContentPane().add(jRbtnCat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jRbtnGrpCategoria.add(jRbtnCat3);
        jRbtnCat3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRbtnCat3.setText("3");
        getContentPane().add(jRbtnCat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jRbtnGrpCategoria.add(jRbtnCat4);
        jRbtnCat4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRbtnCat4.setText("4");
        getContentPane().add(jRbtnCat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jRbtnGrpCategoria.add(jRbtnCat5);
        jRbtnCat5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jRbtnCat5.setText("5");
        getContentPane().add(jRbtnCat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

        jBtnCancelar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jBtnCancelar.setText("Cancelar");
        getContentPane().add(jBtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jBtnGuardar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jBtnGuardar.setText("Guardar");
        getContentPane().add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        jTxtDireccionHotel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTxtDireccionHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 310, -1));

        jTxtNombreHotel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTxtNombreHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 310, -1));

        jTxtCorreoHotel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTxtCorreoHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 310, -1));

        jTxtTelefonoHotel.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        getContentPane().add(jTxtTelefonoHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 310, -1));

        jCmbCiudadesHotel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jCmbCiudadesHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciudad" }));
        getContentPane().add(jCmbCiudadesHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 310, -1));

        jCmbxPaiseHotel.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jCmbxPaiseHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbxPaiseHotelActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbxPaiseHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 310, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 470, 20));

        jCmbxPaiseHotel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jCmbxPaiseHotel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbxPaiseHotel1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbxPaiseHotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 100, -1));

        jCmbCiudadesHotel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jCmbCiudadesHotel1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Ciudad" }));
        getContentPane().add(jCmbCiudadesHotel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCmbxPaiseHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbxPaiseHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbxPaiseHotelActionPerformed

    private void jCmbxPaiseHotel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbxPaiseHotel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbxPaiseHotel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmAddHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmAddHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnCancelar;
    public javax.swing.JButton jBtnGuardar;
    public javax.swing.JComboBox<String> jCmbCiudadesHotel;
    public javax.swing.JComboBox<String> jCmbCiudadesHotel1;
    public javax.swing.JComboBox<String> jCmbxPaiseHotel;
    public javax.swing.JComboBox<String> jCmbxPaiseHotel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButton jRbtnCat1;
    public javax.swing.JRadioButton jRbtnCat2;
    public javax.swing.JRadioButton jRbtnCat3;
    public javax.swing.JRadioButton jRbtnCat4;
    public javax.swing.JRadioButton jRbtnCat5;
    public javax.swing.ButtonGroup jRbtnGrpCategoria;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JTextField jTxtCorreoHotel;
    public javax.swing.JTextField jTxtDireccionHotel;
    public javax.swing.JTextField jTxtNombreHotel;
    public javax.swing.JTextField jTxtTelefonoHotel;
    // End of variables declaration//GEN-END:variables
}
